title: "The Baker Lab"
logo: ./assets/images/OHSU-RGB-4C-REV.svg
author: "Jonathon L. Baker, Ph.D."
description: "Microbiology and Bioinformatics to discover how the bacteria that live in our mouth impact human health and disease"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "./about/index.md",title: "Our Research", url: "https://jonbakerlab.github.io/about/"}
  - {file: "./lab-members/index.md", title: "Our Team", url: "https://jonbakerlab.github.io/lab-members/"}
  - {file: "./publications/index.md", title: "Publications", url: "https://jonbakerlab.github.io/publications/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:bakerjo@ohsu.edu"}
  - {title: Github, icon: github, url: "https://github.com/jonbakerlab"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/jonbakerlab"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

url: https://jonbakerlab.github.io/
